### PR TITLE
Add Image element

### PR DESCRIPTION
**Pull request by elri**
+ test

### CODE REVIEW

**Comment by linkdata** [comment]
Why not just handle it using "HtmlInner()"? There is not really anything special about the "img" tag or the "src" attribute.
Also, as currently written it only handles base64 embedded image data. Normally, "src" would refer to an URL.

**Comment by elri** [comment]
@linkdata 
- [x]  Corrected func name and removed assumptions about src  

HtmlInner(): Didn't feel intuitive, since the Img tag has no inner html, it's a different format overall (no end tag, no type, etc).  Seems like it is possible to use it anyway - just send in empty strings for unused parts and add src to attrs - it conflates the </img> end tag by itself? So no trouble there

**Comment by linkdata** [comment]
Good point about . I've added support for singleton tags in v0.22.0

**Comment by linkdata** [comment]
Img() needs to conform to the pattern of the other functions. Specifically, it needs to have a `jaws.ClickFn` argument.

**Pull request merged**
